/**
 * @fileoverview Helper class for interacting with the OpenAI API. It provides methods for generating jokes, facts, advice, motivation, and quotes using OpenAI's completion endpoint.
 * @module OpenAIHelper
 * @requires openai 
 * @see {@link https://www.npmjs.com/package/openai|OpenAI NPM Package}
 * @requires #lib/env
 * @requires #lib/logger
 * @requires #config/openAI
 * @since 1.0.0
 */

import { getEnv } from "#lib/env";
import openAIConfig from "#config/openAI" with { type: "json" };
import OpenAI from "openai";
import Logger from "#lib/logger";

/**
 * @description The OpenAI model to use for API requests. Reads from the OPENAI_MODEL environment variable, or falls back to the default model from config.
 * @constant {string} openAIModel
 * @default openAIConfig.defaultModel
 * @since 1.0.0
 */
const openAIModel = getEnv("OPENAI_MODEL") ?? openAIConfig.defaultModel;

/**
 * Helper class for interacting with the OpenAI API.
 * Provides methods for generating jokes, facts, advice, motivation, and quotes.
 * @class OpenAIHelper
 * @since 1.0.0
 */
class OpenAIHelper {
    private apiKey: string;
    private model: string;
    public client: OpenAI;

    /**
     * Creates an instance of OpenAIHelper.
     * @constructor
     * @param {string} [apiKey] - The OpenAI API key. If not provided, throws a fatal error.
     * @throws {Error} Throws a fatal error if no API key is provided.
     * @example
     * const helper = new OpenAIHelper(process.env["OPENAI_API_KEY"]);
     */
    public constructor(apiKey?: string | undefined) {
        this.apiKey = this.getAPIKey(apiKey);
        this.model = openAIModel;
        this.client = new OpenAI({
            apiKey: this.apiKey,
        });
    }

    /**
     * Retrieves and validates the OpenAI API key.
     * @function getAPIKey
     * @memberof OpenAIHelper
     * @private
     * @param {string} [apiKey] - The API key to validate.
     * @returns {string} The validated API key.
     * @throws {Error} Throws a fatal error if the API key is not provided.
     */
    private getAPIKey(apiKey?: string | undefined): string {
        if (!apiKey) {
            throw Logger.fatal("You need to retrieve an OpenAI API key for this program to work.\nTo get an API key, please go to: https://openai.com/api/");
        }

        return apiKey;
    }

    /**
     * Sets a new API key for the OpenAI client.
     * @function setAPIKey
     * @memberof OpenAIHelper
     * @public
     * @param {string} key - The new API key to set.
     * @returns {void}
     * @example
     * helper.setAPIKey("sk-new-api-key");
     */
    public setAPIKey(key: string): void {
        this.apiKey = key;
        return;
    }

    /**
     * Sets a new model for OpenAI requests.
     * @function setModel
     * @memberof OpenAIHelper
     * @public
     * @param {string} model - The model identifier to use for future requests.
     * @returns {void}
     * @example
     * helper.setModel("gpt-4");
     */
    public setModel(model: string): void {
        this.model = model;
        return;
    }

    /**
     * Creates a response from the OpenAI API using the provided input and instructions.
     * @function createResponse
     * @memberof OpenAIHelper
     * @private
     * @param {string} input - The input text for the API request.
     * @param {string} instructions - The instructions to guide the API response.
     * @param {string} [model=this.model] - The model to use for the request. Defaults to the instance model.
     * @returns {Promise<OpenAI.Responses.Response & { _request_id?: string | null; }>} The API response object.
     * @example
     * const res = await createResponse("Tell me which programming language is the best for beginners to learn and why.", "Pretend like you're a professional developer explaining it to me.")
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    private async createResponse(input: string, instructions: string, model: string = this.model): Promise<OpenAI.Responses.Response & { _request_id?: string | null; }> {
        const response = await this.client.responses.create({
            model,
            instructions,
            input
        });

        return response;
    }

    /**
     * Generates a joke using the OpenAI API.
     * @function createAJoke
     * @memberof OpenAIHelper
     * @public
     * @async
     * @returns {Promise<string>} A joke generated by the AI.
     * @example
     * const joke = await helper.createAJoke();
     * console.log(joke); // "Why did the chicken cross the road?..."
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    public async createAJoke(): Promise<string> {
        const response = await this.createResponse(openAIConfig["jokeGenerator"]["input"], openAIConfig["jokeGenerator"]["instructions"])
        
        return response.output_text;
    }

    /**
     * Generates a random fact using the OpenAI API.
     * @function findAFact
     * @memberof OpenAIHelper
     * @public
     * @async
     * @returns {Promise<string>} A fact generated by the AI.
     * @example
     * const fact = await helper.findAFact();
     * console.log(fact); // "Did you know that honey never spoils?..."
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    public async findAFact(): Promise<string> {
        const response = await this.createResponse(openAIConfig["factMaker"]["input"], openAIConfig["factMaker"]["instructions"])
        
        return response.output_text;
    }

    /**
     * Generates random advice using the OpenAI API.
     * @function sendSomeRandomAdvice
     * @memberof OpenAIHelper
     * @public
     * @async
     * @returns {Promise<string>} Advice generated by the AI.
     * @example
     * const advice = await helper.sendSomeRandomAdvice();
     * console.log(advice); //"Always be kind to yourself..."
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    public async sendSomeRandomAdvice(): Promise<string> {
        const response = await this.createResponse(openAIConfig["adviceGiver"]["input"], openAIConfig["adviceGiver"]["instructions"])
        
        return response.output_text;
    }

    /**
     * Generates motivational content using the OpenAI API.
     * @function movingMotivation
     * @memberof OpenAIHelper
     * @public
     * @async
     * @returns {Promise<string>} Motivational text generated by the AI.
     * @example
     * const motivation = await helper.movingMotivation();
     * console.log(motivation); // "You are capable of amazing things..."
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    public async movingMotivation(): Promise<string> {
        const response = await this.createResponse(openAIConfig["motivationMan"]["input"], openAIConfig["motivationMan"]["instructions"])
        
        return response.output_text;
    }

    /**
     * Generates a quote using the OpenAI API.
     * @function quoter
     * @memberof OpenAIHelper
     * @public
     * @async
     * @returns {Promise<string>} A quote generated by the AI.
     * @example
     * const quote = await helper.quoter();
     * console.log(quote); // "The only way to do great work is to love what you do..."
     * 
     * @see {@link OpenAIHelper.createResponse} - The general response creation method that calls OpenAI.
     * @since 1.0.0
     */
    public async quoter(): Promise<string> {
        const response = await this.createResponse(openAIConfig["quoter"]["input"], openAIConfig["quoter"]["instructions"])
        
        return response.output_text;
    }
}

export default OpenAIHelper;