/**
 * @fileoverview Type definitions for the OpenAI helper service. Provides TypeScript declarations for the OpenAIHelper class and its methods.
 * @module #services/openAI
 * @since 1.0.0
 */

declare module "#services/openAI" {
  import OpenAI from "openai";

  /**
   * @description Helper class for interacting with the OpenAI API. Provides methods for generating jokes, facts, advice, motivation, and quotes.
   * @class OpenAIHelper
   * @since 1.0.0
   */
  export default class OpenAIHelper {
    /**
     * @description The OpenAI API key used for authentication.
     * @private
     * @type {string}
     */
    private apiKey: string;

    /**
     * @description The OpenAI model identifier used for API requests.
     * @private
     * @type {string}
     */
    private model: string;

    /**
     * @description The OpenAI client instance for making API calls.
     * @public
     * @type {OpenAI}
     */
    public client: OpenAI;

    /**
     * @description Creates an instance of OpenAIHelper.
     * @constructor
     * @param {string} [apiKey] - The OpenAI API key. If not provided, throws a fatal error.
     */
    constructor(apiKey?: string);

    /**
     * @description Sets a new API key for the OpenAI client.
     * @function setAPIKey
     * @public
     * @param {string} key - The new API key to set.
     * @returns {void}
     */
    public setAPIKey(key: string): void;

    /**
     * @description Sets a new model for OpenAI requests.
     * @function setModel
     * @public
     * @param {string} model - The model identifier to use for future requests.
     * @returns {void}
     */
    public setModel(model: string): void;

    /**
     * @description Generates a joke using the OpenAI API.
     * @function createAJoke
     * @public
     * @returns {Promise<string>} A joke generated by the AI.
     */
    public createAJoke(): Promise<string>;

    /**
     * @description Generates a random fact using the OpenAI API.
     * @function findAFact
     * @public
     * @returns {Promise<string>} A fact generated by the AI.
     */
    public findAFact(): Promise<string>;

    /**
     * @description Generates random advice using the OpenAI API.
     * @function sendSomeRandomAdvice
     * @public
     * @returns {Promise<string>} Advice generated by the AI.
     */
    public sendSomeRandomAdvice(): Promise<string>;

    /**
     * @description Generates motivational content using the OpenAI API.
     * @function movingMotivation
     * @public
     * @returns {Promise<string>} Motivational text generated by the AI.
     */
    public movingMotivation(): Promise<string>;

    /**
     * @description Generates a quote using the OpenAI API.
     * @function quoter
     * @public
     * @returns {Promise<string>} A quote generated by the AI.
     */
    public quoter(): Promise<string>;
  }
}
